# Etapa 1: build
FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: servir estático con nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

# Nginx por defecto escucha en 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]